### PR TITLE
Update submodule for hscommon & qtlib

### PR DESCRIPTION
**Pull request by arsenetar**
Fix issues #452 and #489

### CODE REVIEW

**Comment by arsenetar** [comment]
@hsoft I was wonder if we were alright with releasing a 4.0.4 shortly as there is at least one re-occurring issue that is being reported.  Additionally a couple nice fixes (mainly affecting the windows versions).  Does that seem reasonable?

**Comment by hsoft** [comment]
@arsenetar as I wrote in https://github.com/hsoft/dupeguru#current-status-unmaintained a couple of days ago, I really lack the will to continue maintaining dupeGuru. To release v4.0.4, I would have to undust my dying mac mini and hope that it didn't stop working. I could probably make a last effort for a 4.0.4 release, but then what will happen for the v4.0.5?

I'm really glad that you seem to have some will to work on dupeGuru. I wouldn't want to overburden you with the task of maintaining all 3 platforms, but one thing that we could do is to say, for example, that as of now, dupeGuru becomes Windows only (or Windows + Linux if you want). You set up a website somewhere and I change dupeGuru's page to link to your own website. Do you think it's something that could work?

**Comment by arsenetar** [comment]
@hsoft I think we could make something as you suggest work.  I think it would be possible to maintain windows + linux.  I will take a look into building the linux packages to make sure I can figure that out.  I do not have the hardware to build the OSX versions. While it looks like Travis CI could be leveraged to build those packages, I would not have the ability to test / debug beyond that for OSX.

**Comment by hsoft** [comment]
@arsenetar great! let's try this then.

**Comment by arsenetar** [comment]
Ok, so I have a basic site setup at https://dupeguru.voltaicideas.net/.  I am thinking of potentially using the GitHub releases to host the actual file downloads moving forward.  I am thinking of including some additional information on an "About" page as well.  @hsoft let me know what you think.

**Comment by hsoft** [comment]
Windows releases on github? I wonder how you'll be able to manage that. But anyway, whatever works. I'll update dupeGuru's website to link to that URL.

**Comment by Cebtenzzre** [comment]
Well, @arsenetar and @hsoft, is this pull request ready yet?  Or is there more that has to be done before merging or closing it?  Sorry to bother, but I haven't seen a specific reason why it should remain open and waiting.  I'm here because I like this program and use it regularly.

**Comment by hsoft** [comment]
No particular reason. Since I don't maintain dupeguru myself, I expect @arsenetar to merge it himself.

By the way, from the look of it, there's still room for people who would be interested in co-maintainership of the project.

**Comment by Cebtenzzre** [comment]
@hsoft Well, I've only modded python scripts before (never written any, but I work with other languages quite often), and I'm fairly busy with a number of projects (I've somehow gotten into porting Minecraft server plugins), but I might be interested in helping.  With over 200 open issues, I suppose this project needs all the help it can get.

**Pull request merged**
