### PR TITLE
Added 'el' locale

### PR DESCRIPTION
**Pull request by 1kakarot**
added 'el' files and modified qt/preferences_dialog.py
with 'el' supported language.

### CODE REVIEW

**Comment by 1kakarot** [comment]
I hope now I did it correctly.
PRs for all modules and the main app.

**Comment by hsoft** [comment]
Except for some spurious changes in subrepos PR, it looks good to me. Once those sub-PRs are merged, we'll need to update this PR with subrepo references and we'll be good to merge.

That makes me realize that having subrepos complicates the submission of translations a lot. It really shouldn't be that complicated. But I can't think of an alternative.

**Comment by hsoft** [comment]
Was I forgetting about this PR? I think so. I'll have a second look now, I think it's ready to merge. Sorry for the delay.

**Comment by hsoft** [comment]
Thanks!

**Pull request merged**
